remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"
# theme: minimal-mistakes-jekyll
title: GApS
title_separator: "-"
subtitle: A Coding Scheme for Great Apes Signals in ELAN
authors: Emilie Genty, Michael Fuchs
logo: /assets/images/logo.png

doi: <a href="https://zenodo.org/badge/latestdoi/571517799"><img src="https://zenodo.org/badge/571517799.svg" alt="DOI"></a>

# Site Settings
name                     : "E. Genty and M. Fuchs"
description              : "A Coding Scheme for Great Apes Signals in ELAN"
url                      : "https://greatapesgestures.github.io"
# baseurl                  : "/test"
repository               : "GreatApesGestures/GreatApesGestures.github.io"

# # SEO Related
# google_site_verification :

# Site Author
author:
  name             : "E. Genty and M. Fuchs"
#   # avatar           : "/assets/images/bio-photo.jpg"
#   bio              : ""
#   location         : "UNINE"
  links:
   - label: "GitHub"
     icon: "fab fa-fw fa-github"
     url: "https://github.com/GreatApesGestures/GreatApesGestures.github.io"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GreatApesGestures/GreatApesGestures.github.io"

plugins:
  - jekyll-include-cache